Advanced.Net/SportsPro/SportsPro/Models/Incident.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentID { get; set; }
        public int CustomerID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Technician Technician { get; set; }

        public static string CustomerIncidentDisplay(IncidentViewModel IncidentVM)
        {

            return "Incident for product " + IncidentVM.ProductName + " closed " + IncidentVM.DateClosed + " (" + IncidentVM.Description + ")";
        }
    }
}

Advanced.Net/SportsPro/SportsPro/Models/IncidentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace SportsPro.Models
{
    public class IncidentViewModel
    {
        public int IncidentID { get; set; }
        public int CustomerID { get; set; }      
        public string ProductCode { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public string ProductName { get; set; }
        public string TechnicianName { get; set; }




    }
}

Advanced.Net/SportsPro/SportsPro/Models/Incidents.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Advanced.Net/SportsPro/SportsPro/Controllers/IncidentsController.cs
using SportsPro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsPro.Controllers
{
    [Authorize(Roles = "Technician")]
    public class IncidentsController : Controller
    {
        // GET: Technician
        public ActionResult Index()
        {
            dw_TechSupportDBContext db = new dw_TechSupportDBContext();
           
            var getCustomerList = db.Customers.OrderBy(x => x.Name).ToList();
            SelectList list = new SelectList(getCustomerList, "CustomerId", "Name","--Select A Customer --");
            ViewBag.Customers = list;
            ViewBag.Header1 = "Product/Incident";
            ViewBag.Header2 = "Tech name";
            ViewBag.Header3 = "Opened";
            ViewBag.Header4 = "Closed";


            return View();
        }

        [HttpPost]
        public ActionResult Index(string dummy)
        {
            dw_TechSupportDBContext db = new dw_TechSupportDBContext();

            var selectedCust = new Customer();
 
            ViewBag.SelectedItem = Request["ddlCustomers"];
            var getCustomerList = db.Customers.OrderBy(x => x.Name).ToList();
            SelectList list = new SelectList(getCustomerList, "CustomerId", "Name", ViewBag.SelectedItem);
            ViewBag.Customers = list;
            ViewBag.Header1 = "Product/Incident";
            ViewBag.Header2 = "Tech name";
            ViewBag.Header3 = "Opened";
            ViewBag.Header4 = "Closed";
            dw_TechSupportIncidentTechProd db2 = new dw_TechSupportIncidentTechProd();

            List<Incident> incidentList = db2.Incidents.ToList();
            
            //List<Incident> custIncident = (List<Incident>)(db2.Incidents.Where(x=>x.CustomerID == Convert.ToInt32(Request["ddlCustomer"])));
            IncidentViewModel incidentVM = new IncidentViewModel();


            //April Hauk assisted with the need and location placement by providing a general example of a join in mvc

            List<IncidentViewModel> incidentVMList = (from incident in db2.Incidents
                                                        join technician in db2.Technicians on incident.TechID equals technician.TechID 
                                                        join product in db2.Products on incident.ProductCode equals product.ProductCode 
                                                        select new IncidentViewModel
                                                        {
                                                            CustomerID = incident.CustomerID,
                                                            ProductCode = incident.ProductCode,
                                                            ProductName = incident.Product.Name,
                                                            TechID = incident.TechID,
                                                            TechnicianName = incident.Technician.Name,
                                                            DateOpened = incident.DateOpened,
                                                            DateClosed = incident.DateClosed,
                                                            Description = incident.Description
                                                        }).ToList();

            return View(incidentVMList);


        }


    }
}

Advanced.Net/SportsPro/SportsPro/Views/Incidents/Index.cshtml
@model  IEnumerable<SportsPro.Models.IncidentViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Index", "Incidents", FormMethod.Post, new { id = "TheForm" }))
{
    <div class="row">
        <label class="col-md-offset-1 col-md-3">Select a customer:</label>
        <span class="col-md-4">@Html.DropDownList("ddlCustomers", (SelectList)ViewBag.Customers, "--Select Customer--", new { onchange = "this.form.submit();" }) </span>
    </div><br /><br />
}
<div class="container">
    <table id="CustomerIncidentDataList" class="table table-striped ">
        <thead class="thead-inverse">
            <tr>
                <th class="col-lg-3">Product/Incident</th>
                <th class="col-lg-3">Tech Name</th>
                <th class="col-lg-3">Date Opened</th>
                <th class="col-lg-3">Date Closed</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    if ((int)@item.CustomerID == Convert.ToInt32(ViewBag.SelectedItem))
                    {
                        <tr>
                                <td class="col-lg-3">@item.ProductName</td>
                                <td class="col-lg-3">@item.TechnicianName</td>
                                <td class="col-lg-3">@item.DateOpened.ToShortDateString()</td>
                                <td class="col-lg-3">@item.DateClosed <br /></td>
                                <td colspan="4" class="col-lg-12">@item.Description</td>
                            
                        </tr>
                    }
                }
            }
            <tr></tr>
        </tbody>
    </table>
</div>

Advanced.Net/SportsPro/SportsPro/Views/Incidents/Test.cshtml
@model SportsPro.Models.IncidentViewModel
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>
@if (Model != null) {
    <ul class="list-group">
        <li class="list-group-item active">Incident Information</li>
        <li class="list-group-item active">Customer ID: @Model.CustomerID</li>
        <li class="list-group-item active">Product: @Model.ProductCode</li>
        <li class="list-group-item active">Tech: @Model.TechID</li>
        <li class="list-group-item active">Opened: @Model.DateOpened.ToShortDateString()</li>
        <li class="list-group-item active">Closed: @Model.DateClosed.Value.ToString("MM'/'dd'/'yyyy")</li>
        <li class="list-group-item active">Incident: @Model.Description</li>
    </ul>

}